### ISSUE TITLE
Problem with target selection

### ISSUE THREAD

**Issue by hamid13r** [eisfabian/SPACEtomo#8] opened 2024-10-21 00:14 UTC
Dear Fabian,

I am making progress with SPACEtomo but have this problem with target selection. If I don't go for manual targeting the GUI won't come up saying `no segmentation found`.

If I go with manual targeting the GUI comes up but no matter what I do with left click I get this message and nothing happens:
`Traceback (most recent call last):
  File "C:\ProgramData\SerialEM\spacetomo\SPACEtomo-main\SPACEtomo\SPACEtomo_tgt.py", line 67, in mouseClick
    if dpg.is_mouse_button_down(dpg.mvMouseButton_Left) and dpg.is_key_down(dpg.mvKey_Shift):
AttributeError: module 'dearpygui.dearpygui' has no attribute 'mvKey_Shift'`
![Screenshot 2024-10-20 at 5 14 19 PM](https://github.com/user-attachments/assets/b79768d4-9948-4e75-bb7f-3e2a3f14890a)

Any idea what I am doing wrong?

**Comment by eisfabian** [comment] 2024-10-21 06:53
Hi Hamid,

Thanks for giving it a shot!

Does it try to create a segmentation and fail when you run `manual_selection=False`? You should be able to check either the SPACE_maps folder or the external_map_dir you gave it. Is there a *_seg.png file for the lamella map? If not, look for a log and an err file of the lamella MM map. That might give you a clue about what went wrong!

The second problem is caused by a recent update in the GUI library to 2.0. Try installing `dearpygui==1.11.*` instead to fix it for now.

Version 1.2 is around the corner which should fix all of this and much more. I've been in the "final" stages of testing for weeks now, but keep finding little bugs to squash. :P

Best,
Fabian

**Comment by hamid13r** [comment] 2024-10-24 02:45
I did get the png files but I am not sure if I am getting it consistently. Installing the `dearpygui==1.11.*` didnt go well, but I think it is wise for me to wait for 1.2 and work out my problems there. 

Good luck with the bugs ;)

**Comment by eisfabian** [comment] 2024-11-22 08:02
Version 1.2 is now finally up! I will close the issue for now. Please reopen it if the problem persists!

**Closed as completed by eisfabian** 2024-11-22 08:02 UTC
